### ISSUE TITLE
Getting Killed after importing about 20k records

### ISSUE THREAD

**Issue by FREEZX** [glynnbird/couchimport#1]
Hi,
I'm trying to import a fairly big data set (~3 million entries) by using couchimport, but the process always gets killed for some reason.
Here's my output:

```
root@leb-01122233:~# cat dailydump.txt | couchimport
******************
 COUCHIMPORT - configuration
   {"COUCH_URL":"http://****:****@127.0.0.1:5984","COUCH_DATABASE":"torrents","COUCH_TRANSFORM":null,"COUCH_DELIMETER":"|"}
******************
Written 500  ( 500 )
Written 500  ( 1000 )
...
Written 500  ( 21500 )
Written 500  ( 22000 )
Written 500  ( 22500 )
Written 500  ( 23000 )
Killed
```

any ideas?

**Comment by glynnbird** [comment]
I suspect the OS is killing it because of excessive memory usage. Let me see if I can find a way of limiting how many lines are buffered in the app.

**Comment by glynnbird** [comment]
I've been unable to reproduce this. Running on my Mac, with Node.js 0.10.32, I'm happily importing 19m rows of data. I'm up to 0.5m at the moment.

**Comment by FREEZX** [comment]
I'm running it on a VPS with 512MB ram, also node.js 0.10.32.

**Comment by glynnbird** [comment]
Is it possible to try this on a machine with more RAM? My 19m row import completed without an error, but then I do have 8Gb of RAM on my machine.

**Comment by FREEZX** [comment]
I believe that doing it on a machine with more RAM will have the same results as yours.
Would you like me to give you access to the machine i'm working on so you can test there?

**Comment by netsmile** [comment]
Hi Glynn

Written 500  ( 17000 )
FATAL ERROR: JS Allocation failed - process out of memory

Using the following :
-  latest commit b0f62bdcb9
- Win 7 64-bit 1.13.00.AK B15
- git-gui version 0.19.GITGUI
- git version 1.9.5.msysgit.1
- Tcl/Tk version 8.5.13

Its always 17k for me.
Same result if I decrease 500 element buffer to "COUCH_BUFFER_SIZE": 250,

**Comment by glynnbird** [comment]
I've add a "pause" into the Node.js stream to try and prevent the input side of the stream (reading data and transforming it) swamping the output side (writing to CouchDB). So please try version 0.0.12 and see if that helps.

I haven't had a problem running this utility on my machine (a Mac with 16GB) of memory
