### ISSUE TITLE
Limit the requests per second this library makes

### ISSUE THREAD

**Issue by glynnbird** [glynnbird/couchimport#127]
When using with Cloudant Lite plan on Bluemix there is a rate limit imposed on customers. Users exceed that rate of API calls will start receiving HTTP 429 replies. 

When importing large data sets, it's best to stick to a maximum API call (say 5 per second) to avoid the 429 responses.

**Comment by glynnbird** [comment]
I have a [qrate](https://www.npmjs.com/package/qrate) library which should make it easy enough to rate limit the queued work

**Comment by webdevlamp** [comment]
@glynnbird ,

I have been working on an import script to import CSV data into cloudant database. I have about 1.3 million records in CSV file. Using couchimport importStream function i have tried to import data. However it ended up with **Error: Request failed with status code 429**. It may be useful for me to know how did you manage to use **qrate** along with couchimport? an example or a code snippet will be much more helpful for me.

Thanks

**Comment by glynnbird** [comment]
@webdevlamp I'd forgotten about this - I might have a go at implementing that just now. :)

**Comment by webdevlamp** [comment]
@glynnbird , Thanks I am looking forward to it, as i have been stuck with developing import script just due to this error.

**Comment by glynnbird** [comment]
Well that was easy.

So couchimport v1.4.3 is just released. It has a new parameter

- `--maxwps` on the command line
- `maxwps` when used programmatically
- `COUCH_MAX_WPS` as an environment variable

You can use this to limit the number writes per second that are attempted.

e.g.

```
cat housesales.csv | couchimport --db hp --delimiter "," --parallelism 3 --maxwps 5
```

^ do up to three writes in parallel, but make sure that no more than 5 write requests are dispatched in the same second (rate limiting).

**Comment by webdevlamp** [comment]
@glynnbird thanks for your quick response. Following is the script that i have been trying to execute, but it does not work even after version update for couchimport and also additional params like maxwps, parallelism being set in the options.
`'use strict'

const couchimport = require('couchimport');
const config = require('./config.json');

const AWS = require('aws-sdk');
const s3 = new AWS.S3({
  accessKeyId: config.accessKeyId,
  secretAccessKey: config.secretAccessKey
});

const opts = {
  "delimiter": ";",
  "url": config.CloudantUrl,
  "database": "anixedb",
  "overwrite": true,
  "maxwps": 5,
  "parallelism": 3
};

const processImport = () => {
  return new Promise((resolve, reject) => {
    const params = {
      Bucket: config.s3Bucket
    };
    s3.listObjects(params, (err, data) => {
      if(err) {
        console.error(err);
        reject(err);
      }
      if(data.Contents != null && data.Contents.length > 0) {

        data.Contents.map((item) => {

          let getParams = { Bucket: config.s3Bucket, Key: item.Key };
          let fileReadStream = s3.getObject(getParams).createReadStream();

          couchimport.importStream(fileReadStream, opts, function(err, data) {

            if(err) {
              console.log("err", err);
            }

            console.log("done");

          }).on("written", function(data) {
            console.log(data);

          }).on("writeerror", function(err) {
            console.log(data);
          });

        });

      } else {
        console.log("No CSV files found.");
        resolve();
      }
    });
  });
};

processImport();
`

**Comment by glynnbird** [comment]
I think your problem is that you are running several imports in parallel. So although each on individually has a controlled rate of `parallelism`/`maxwps`, because you importing several files at once, you are exhausting your provisioned throughput because the total writes you are doing exceeds the maximum. 

```
data.Contents.map((item) => { 
  // whatever is here gets run in parallel with other members of data.Contents
```

Trying running one import at a time?

**Comment by webdevlamp** [comment]
Hi Glynnbird,

Thanks for your response.

You pointed out correct spot, but that is for possible multiple files will
be there at s3 bucket in future, as of now there is only 1 CSV file to be
tacked.
One thing to bring to your notice here is the CSV file is containing about
1.3 million records to be imported in cloundant database in the form of
JSON documents.
I am not sure if couchimport is capable to handle such large amount of data
coming from CSV file?
You may have noticed i am using read stread to read CSV data from s3
bucket, so it must be handling the CSV file better compared to file system
function, isn't it?
Do you know an alternative solution to tackle huge CSV file import into
cloudant database?

Thanks,
Mayur

**Comment by glynnbird** [comment]
> I am not sure if couchimport is capable to handle such large amount of data
coming from CSV file?

It's not really the size of the file, it's the number of requests per second that is causing 429 responses. A simple solution is to provision more throughput in your Cloudant instance. The Cloudant Standard plan offers a range of paid-for plans: you could "scale up" your capacity to do the import and scale back down later.

> You may have noticed i am using read stread to read CSV data from s3
bucket, so it must be handling the CSV file better compared to file system
function, isn't it?

If you'd used the file system function, it simply gets a ReadStream from the file and calls `importStream`, so no benefit really

> Do you know an alternative solution to tackle huge CSV file import into
cloudant database?

This is the only one I know of. It's simply making bulk write calls to your database - I recommend provisioning a larger service. Or write to a local CouchDB service and then use replication to move the data from CouchDB --> Cloudant (replication will just be doing bulk writes, so there's no real difference).

**Comment by webdevlamp** [comment]
Thanks @glynnbird , I will try the approach(replication) you suggested.
