### ISSUE TITLE
Export custom data from object 

### ISSUE THREAD

**Issue by sandip-jadhav** [glynnbird/couchimport#165]
`{
  "_id": "d4ebc3b9397ba3faaacde2bfb80089e7",
  "_rev": "2-69b7ea5b6dd7495ff3d26a0fc5630825",
  "personal": {
    "firstName": "Dan",
    "lastName": "Denney",
    "dob": "12/26/87",
    "gender": "male"
  },
  "work": {
    "workTitle": "Software Engineer",
    "workCompany": "Code School"
  },
  "social": {
    "website": "dandenney.com",
    "emailId": "dan@gmail.com",
    "twitter": "dandenney1",
    "facebook": "dandenney"
  },
  "address": {
    "houseNumber": "52",
    "streetName": "main street",
    "city": "lodz",
    "country": "poland"
  }
}`

Want to export simple object with  attributes firstName, lastName & company
We created transform.js 
`// example transformation function
// -- remove leading and trailing quotes
var x = function(doc) {	 
 doc.firstName = doc.personal.firstName;
 doc.lastName= doc.personal.lastName;
 doc.company = doc.work.workCompany;
  delete doc.work;
  delete doc.social;
  delete doc.address;
  return doc;
}
module.exports = x;`

Command used 
couchexport --url http://localhost:5984 --database tomtomdemo --delimiter "," --transform "D:\Places\optimus\Tools\couchDbTools\transform.js" > test_1.csv

Result : not expected 
_id,personal,work,social,address
d4ebc3b9397ba3faaacde2bfb80089e7,[object Object],[object Object],[object Object],[object Object]

**Comment by glynnbird** [comment]
Your transform function leaves an object behind:

```js
{ _id: 'd4ebc3b9397ba3faaacde2bfb80089e7',
  _rev: '2-69b7ea5b6dd7495ff3d26a0fc5630825',
  personal: 
   { firstName: 'Dan',
     lastName: 'Denney',
     dob: '12/26/87',
     gender: 'male' },
  firstName: 'Dan',
  lastName: 'Denney',
  company: 'Code School' }
```

Try `delete doc.personal` in your transform function?

**Comment by sandip-jadhav** [comment]
Updated transform function by adding delete doc.personal
`//Get simple attribute from nested object
var x = function(doc) {	 
 doc.firstName = doc.personal.firstName;
 doc.lastName= doc.personal.lastName;
 doc.company = doc.work.workCompany;
  delete doc.work;
  delete doc.social;
  delete doc.address;
  delete doc.personal;
  return doc;
}
module.exports = x;`

Same result 
_id,personal,work,social,address
d4ebc3b9397ba3faaacde2bfb80089e7,[object Object],[object Object],[object Object],[object Object]

**Comment by glynnbird** [comment]
Actually @sandip-jadhav I know what's happening here. The transform step is only used on `couchimport` not on `couchexport` but actually what you have suggested here is a reasonable use-case, so I'll have a go (tomorrow) to implement transformation on the export process too.

I'll use this issue to track progress.
