### ISSUE TITLE
IMPORT BIGDATA

### ISSUE THREAD

**Issue by cfjimenez** [glynnbird/couchimport#34]
I'm trying to load a large amount of data 100GB size csv format, and use the --parallelism parameters and --buffer but I can not improve loading time.
 Can you help me solve this or How to consume more RAM ??

**Comment by glynnbird** [comment]
the limiting factor is perhaps the size of your CouchDB/Cloudant cluster or the bandwidth between you and the server. A Cloudant cluster scale to add more throughput e.g. a six-node cluster can deal with twice as many requests as a 3 node cluster,

**Comment by cfjimenez** [comment]
ok , I understand but I am using couchdb , you know how I can do ?

**Comment by glynnbird** [comment]
CouchDB 2.0 can be deployed as a cluster http://couchdb.apache.org/developer-preview/2.0/

This should give you the ability to add more nodes which should give you a higher capacity for write throughput.
