### ISSUE TITLE
Confused about JSONPath parameter

### ISSUE THREAD

**Issue by mikemccawley** [glynnbird/couchimport#42]
Want to create a test database.
Production database is ~ 3M rows (Cloudant)
I query out my random sample with a _view, and use ?include_docs=true with ccurl piped to a file.

Now I got JSON like this:
```
{"total_rows":10000,"offset":0,"rows":[
   {"id":" 61001",
    "key":" 61001",
    "value":1,
    "doc": {
       "_id":"61001",
       "_rev":"7-7b34fbeadcb40c5c7034cd3628da5d7c",
       "field1":""}
   },
```
etc.

So, to import that back up into a new Cloudant database, doing this:

```
export COUCH_DATABASE="new-db-small"
export COUCH_PARALLELISM=10
export COUCH_FILETYPE=json

export COUCH_JSON_PATH="rows.*.doc"
cat ./data/tickets_small.json | couchimport
```

and I'm not finding the documents in the source json.  I tried: 
rows.*    :  was wrong, got the id, key, value, doc properties 
.rows[*].doc   : which should work if it was a JSONpath per Stefan Goessner, I think
and a bunch of trial and error.
So, what am I missing?  I'm certain you've done exactly this, considering the output of a view.

**Comment by mikemccawley** [comment]
Answered my own problem.  I forgot to delete the _rev property in my transform.
All is good, but was puzzled by the lack of a "conflict" error message.

**Comment by glynnbird** [comment]
I think that the reason you didn't get an error @mikemccawley is that the CouchDB bulk api doesn't return a 40* error when one or more documents fail to write, it returns with a 202. So my code didn't detect the error, so didn't output any debug.
