### ISSUE TITLE
Crashing Consistently

### ISSUE THREAD

**Issue by ghost** [glynnbird/couchimport#51]
Loading a JSON file to Cloundant.  Any file throws and error around the 117000 record mark.

Posting the console dump here:

<--- Last few GCs --->

   35952 ms: Scavenge 1399.3 (1458.1) -> 1399.3 (1458.1) MB, 1.1 / 0 ms (+ 1.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   36882 ms: Mark-sweep 1399.3 (1458.1) -> 1398.9 (1458.1) MB, 930.4 / 0 ms (+ 1.0 ms in 1 steps since start of marking, biggest step 1.0 ms) [last resort gc].
   37793 ms: Mark-sweep 1398.9 (1458.1) -> 1398.9 (1458.1) MB, 910.4 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x30eacf1e3ac1 <JS Object>
    2: write [/usr/local/lib/node_modules/couchimport/node_modules/jsonparse/jsonparse.js:~80] [pc=0x38b956c216c0](this=0x1cf13944ecc1 <a Parser with map 0x288e820a8131>,buffer=0xdf746b4d31 <an Uint8Array with map 0x288e82005759)
    3: /\* anonymous */ [/usr/local/lib/node_modules/couchimport/node_modules/JSONStream/index.js:~20] [pc=0x38b956ca4417] (this=0x1cf13944ee19 <a Stream with map 0x2...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6

**Comment by glynnbird** [comment]
This is pretty clearly an "out of memory" error. I've made enhancements to couchimport before to try and prevent it from running out of memory, mainly to pause the input stream before writing to Cloudant, to prevent incoming file data (which is much faster to read from disk than to write to the network) from spooling endlessly into memory. This is done here: https://github.com/glynnbird/couchimport/blob/master/includes/writer.js#L78

The library always stays in the "writer.js" module (https://github.com/glynnbird/couchimport/blob/master/includes/writer.js#L38) until the buffer has fallen to a reasonable level. Then the stream is unpaused and the next batch of data arrives. 

I've certainly imported larger data sets than 120000 records using couchimport - the biggest I've done is around the 3m mark.
