### ISSUE TITLE
Approach to capture errors when running from the command line?

### ISSUE THREAD

**Issue by RussH1974** [glynnbird/couchimport#59]
I'll start by saying that couchimport is blazing fast when importing documents into Cloudant, no complaints there!

I'm calling couchimport from the command line to import large JSON files containing 60k documents per file, or so.  Is there a way I can get the utility to tell me which documents failed to write, for example, due to revision conflict errors?

cat inv_1.json | couchimport --db invoices --type json --jsonpath "docs.*"

**Comment by RussH1974** [comment]
I've implemented a quick node.js script ... but I'm not getting any output from the call to importFile, I was at least expecting to get a "writeerror" event.

#!/usr/bin/env node

var couchimport = require('couchimport');
var apiKey = "***";
var apiPW = "***";
var hostNm = "abc.cloudant.com"
var cldUrl = "https://" + apiKey + ":" + apiPW + "@" + hostNm;

var dbNm = "xyz";

var opts = { COUCH_URL: cldUrl, COUCH_DATABASE: dbNm, COUCH_FILETYPE: "json", CO
UCH_JSON_PATH: "docs.*" };

var jsonFile = "/dev/shm/SOE/inv_test.json";

console.log(cldUrl);
console.log(opts);

couchimport.importFile(jsonFile, opts, function(err,data) {
  console.log("Imported file: " + jsonFile,err,data);
}).on("written", function(data) {
  console.log(data);
}).on("writeerror", function(data) {
  console.log(data);
});

console.log("After call to importFile: " + jsonFile);

process.exit(0);

**Comment by glynnbird** [comment]
It's not unreasonable to expect a "writerror" event but I'm afraid that's not how the code is written. Couchimport uses the CouchDB bulk write API. The API call may succeed (i.e. it doesn't return 4xx/5xx return code) but individual documents may or may not get written. This would happen if you are trying to insert a document that already exists, for example. 

The code doing this is here:
https://docs.cloudant.com/document.html#bulk-document-validation-and-conflict-errors

Notice that it only fires a `writeerror` if the request as a whole failed, not on individual, per-document errors.

I could modify the library to fire individual "documentwriteerror" events for each failed document perhaps?

But as it stands, no errors are reported or fire events, other than massive "I couldn't find the server" errors.

**Comment by RussH1974** [comment]
Gotcha -- yeah, that's exactly what I'm looking for, the errors reported by the call to _bulk_docs
[{"id":"000000098639358150100001073","error":"conflict","reason":"Document updat
e conflict."},{"id":"00000027992626156550100812902","error":"conflict","reason":
"Document update conflict."}]

My reason for turning to couchimport is that _bulk_docs isn't able to digest large JSON files, but then after the mass import, I need to be able to go back and detect individual documents that failed so they can be requeued and attempted to load again.

The ugliness is in order to produce that report, the output from _bulk_docs needs to be parsed to indicate all of the IDs that failed for one reason or another.

**Comment by glynnbird** [comment]
Ok I'll have a go at that tomorrow - it would definitely be a useful feature. I'll post progress here.

**Comment by glynnbird** [comment]
Ok! version 0.3.2 of `couchimport` is out.

You'll see that you get a count of total documents written and total failed documents now. Not only that you can listen to the "written" event to get per-batch status counts and the "writefail" event to get notified of individual failures.

**Comment by RussH1974** [comment]
Great!  Thanks Glynn -- I'll experiment with this today and perhaps be off and running again.
