### ISSUE TITLE
Not getting the writefail event as expected

### ISSUE THREAD

**Issue by RussH1974** [glynnbird/couchimport#62]
I'm passing in a file I know should be causing document conflicts, but I'm receiving the written event instead of the writefail.  Any thoughts?

couchimport.importFile(jsonFile, opts, function(err,data) {
  console.log("Imported file: " + jsonFile,err,data);
}).on("writefail", function(data) {
  console.log(data);
  console.log("Writefail");
}).on("written", function(data) {
  console.log(data);
  console.log("Written");
}).on("writeerror", function(data) {
  console.log(data);
  console.log("WriteError");
});

{ documents: 2, total: 2 }
Written
Imported file: /dev/shm/SOE/inv_test.json null { total: 2 }

**Comment by RussH1974** [comment]
I thought I'd verify that I have the latest version of couchimport installed ... but 3.9.0 doesn't match up with anything I'm seeing in the release thread.

npm -v couchimport
3.9.0

**Comment by glynnbird** [comment]
uh!? I release https://www.npmjs.com/package/couchimport yesterday with version 0.3.2.

ah `npm -v` gives you the version of npm :)

**Comment by glynnbird** [comment]
`npm -g list couchimport` is what you want.

**Comment by glynnbird** [comment]
The fact that you're getting `{ documents: 2, total: 2 }` without `failed` and `totalfailed` in means your running an older version I expect.

**Comment by RussH1974** [comment]
I'm overlooking something easy ...

npm -g list couchimport
/usr/lib
âââ couchimport@0.3.2

And my package.json contains:
    "dependencies": {
      "couchimport": "latest"
    },

I must be missing a step though ...

**Comment by glynnbird** [comment]
Just tried it myself: 

```sh
> cat guitars.tsv | couchimport --db friday
  couchimport ****************** +0ms
  couchimport configuration +4ms
  couchimport {
 "COUCH_URL": "http://localhost:5984",
 "COUCH_DATABASE": "friday",
 "COUCH_DELIMITER": "\t",
 "COUCH_FILETYPE": "text",
 "COUCH_BUFFER_SIZE": 500,
 "COUCH_JSON_PATH": null,
 "COUCH_TRANSFORM": null,
 "COUCH_META": null,
 "COUCH_PARALLELISM": 1
} +2ms
  couchimport ****************** +0ms
  couchimport Written ok:26 - failed: 0 -  (26) +582ms
  couchimport { documents: 26, failed: 0, total: 26, totalfailed: 0 } +1ms
  couchimport writecomplete +86ms { total: 26, totalfailed: 0 }
  couchimport Import complete +0ms
```

```sh
> which couchimport
/usr/local/bin/couchimport
```

You could try:

```
> cat /usr/local/lib/node_modules/couchimport/package.json
{
...
  "version": "0.3.2"
}
```

To make sure?

**Comment by RussH1974** [comment]
I'm on the right track now at least -- I had a local node_modules directory that was storing version 0.3.1.  I deleted that, and now couchimport under /usr/lib/node_modules/ is showing version 0.3.2.

Unfortunately, my script can no longer find couchimport, so there's a configuration step I missed somewhere, likely related to having that local node_modules directory.

**Comment by glynnbird** [comment]
ok you can delete the global one with `npm -g remove couchimport` and just reinstall your local one.... as you're using it programmatically, that's where it should live.

**Comment by RussH1974** [comment]
I'll go back to installing it locally -- that makes good sense, as you wouldn't want 100 applications all pointing to a global package (would be impossible to upgrade consistently).

And, you can close this one -- it was just me being confused over where couchimport is installed, the output looks great!

{ id: '00000092204C778150100002348',
  error: 'conflict',
  reason: 'Document update conflict.' }
Writefail
{ id: '00000279926C26136550100812902',
  error: 'conflict',
  reason: 'Document update conflict.' }
Writefail
{ documents: 0, failed: 2, total: 0, totalfailed: 2 }

**Comment by glynnbird** [comment]
Great thanks for the feedback. `couchimport` is better for this feature. Hurrah for open-source!
