### ISSUE TITLE
Getting writefail events even for successful document inserts

### ISSUE THREAD

**Issue by RussH1974** [glynnbird/couchimport#63]
Almost there -- and looking good, except I'm getting a writefail for every document insert, when they're succeeding?

Writefail
{ id: '01532024366550100050901',
  rev: '3-d8fe0cefe3cdc9914d3040d425ea84ff' }
Writefail
{ id: '01532329456550100051600',
  rev: '3-0321a1818f40d1bbf5a07412718bc15c' }
Writefail
{ id: '01532420316550100015440',
  rev: '2-fe828a1c6bfd16ee3963d6b415e58454' }
{ documents: 0, failed: 500, total: 0, totalfailed: 6500 }

But, I checked in Cloudant ... the document inserts are definitely succeeding.

**Comment by glynnbird** [comment]
Ok I've deployed version 0.3.3 which should fix this.
